name: Publish to gh-pages

on:
  workflow_call:
    inputs:
      semvertag:
        required: true
        type: string

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: docs
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Build
        run: |
          python -m build
          sphinx-build -b html docsrc/source build/docs
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/docs
          target-folder: ${{ inputs.semvertag }}